const constants = {
  TOGGLE_ELEMENT: "TOGGLE_ELEMENT",
  SLIDE_CHANGE: "SLIDE_CHANGE",
  SLIDE_NEXT: "SLIDE_NEXT",
  SLIDE_PREV: "SLIDE_PREV",
  INPUT_CHANGE: "INPUT_CHANGE",
  FORM_SEND: "FORM_SEND",
  ADD_SLIDE: "ADD_SLIDE",
  ADD_SLIDE_SUBMIT: "ADD_SLIDE_SUBMIT",
  DELETE_SLIDE: "DELETE_SLIDE"
};

export default constants;
